version: '3'
services:
  mysql:
    image: mysql:5.7.20
    environment:
    - MYSQL_USER=root
    - MYSQL_ALLOW_EMPTY_PASSWORD=NO
    ports:
    - 3306:3306
    command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8mb4 --explicit_defaults_for_timestamp